---

collections:
  - name: https://github.com/azimuth-cloud/ansible-collection-terraform
    type: git
    version: 0.5.0
  - name: openstack.cloud
    version: 1.8.0
  - name: ansible.posix # for mount module

roles:
  - src: https://github.com/stackhpc/ansible-role-os-manila-mount.git
    name: stackhpc.os-manila-mount
    version: v24.5.0
