---

- name: Provision infrastructure
  hosts: openstack
  roles:
    - cluster_infra
  post_tasks:
    - name: Wait for Monitoring to become available
      uri:
        url: "http://{{ zenith_fqdn_monitoring }}"
        method: GET
        follow_redirects: safe
      register: monitoring_uri
      changed_when: false
      # The task fails if there is an error querying the endpoint
      # An SSL error is indicated as -1, which will occur while cert-manager fetches certificates
      # A 404 is expected until the Zenith service has started
      failed_when: >-
        monitoring_uri.status < 0 or
        monitoring_uri.status == 404 or
        monitoring_uri.status >= 500
      retries: 60
      delay: 10
      until: "monitoring_uri is not failed"
      when: (cluster_state | default('present')) == 'present'
    
    - name: Wait for webconsole to become available
      uri:
        url: "http://{{ zenith_fqdn_webconsole }}"
        method: GET
        follow_redirects: safe
      register: webconsole_uri
      changed_when: false
      # The task fails if there is an error querying the endpoint
      # An SSL error is indicated as -1, which will occur while cert-manager fetches certificates
      # A 404 is expected until the Zenith service has started
      failed_when: >-
        webconsole_uri.status < 0 or
        webconsole_uri.status == 404 or
        webconsole_uri.status >= 500
      retries: 60
      delay: 10
      until: "webconsole_uri is not failed"
      when: (cluster_state | default('present')) == 'present'

    - name: Add instance to inventory
      add_host:
        name: "{{ cluster_name }}-{{ cluster_type }}"
        groups: workstation
        ansible_host: "{{ cluster_floating_ip_address }}"
        ansible_user: ubuntu
        ansible_ssh_private_key_file: "{{ cluster_ssh_private_key_file }}"
      when:
        - cluster_floating_ip_address is defined and cluster_floating_ip_address
        - (cluster_state | default('present')) == 'present'

- hosts: workstation # so only happens with FIP
  gather_facts: no
  become: yes
  vars:
    os_manila_mount_shares:
      - share_name: azimuth-project-share
        mount_path: /project
        mount_user: root
        mount_group: root
        mount_mode: ugo=rwX
  tasks:
    - name: Configure Manila project share
      include_role:
        name: stackhpc.os-manila-mount
      when: cluster_project_manila_share | default(false) | bool

# Write the outputs as the final task
- hosts: localhost
  tasks:
    - debug: 
        var: outputs
      vars:
        fip_address: "{{ hostvars[groups['openstack'][0]].cluster_floating_ip_address }}"
        outputs: >-
          {{-
            { "cluster_access_ip": fip_address }
          }}
      when: fip_address is defined and fip_address
