---

- name: Convert the floating IP id to an address for Terraform
  when:
    - cluster_floating_ip is defined
    - cluster_floating_ip
  block:
    - name: Look up floating ip
      azimuth_cloud.terraform.os_floating_ip_info:
        floating_ip: "{{ cluster_floating_ip }}"
      register: cluster_floating_ip_info

    - name: Set floating IP address fact
      ansible.builtin.set_fact:
        cluster_floating_ip_address: "{{ cluster_floating_ip_info.floating_ip.floating_ip_address }}"

- name: Install Terraform binary
  ansible.builtin.include_role:
    name: azimuth_cloud.terraform.install

- name: Make Terraform project directory
  ansible.builtin.file:
    path: "{{ terraform_project_path }}"
    state: directory
    mode: "0755"

- name: Template Terraform files into project directory
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ terraform_project_path }}/{{ item }}"
    mode: "0644"
  loop:
    - outputs.tf
    - providers.tf
    - resources.tf

- name: Provision infrastructure
  ansible.builtin.include_role:
    name: azimuth_cloud.terraform.infra
  vars:
    terraform_rebuild_nodes: "{{ azimuth_update_reason == 'patch' }}"
